In [2]:
# -*- coding: utf-8 -*-
"""
Realiza cálculos demográficos

@author: Patrick Alves
patrickalves@ufpa.br

"""

import pandas as pd

In [3]:
# Carrega as bases populacionais
pop_homens = pd.read_csv("../datasets/IBGE/pop_homens_IBGE_2013.csv", index_col = 0)    
pop_mulheres = pd.read_csv("../datasets/IBGE/pop_homens_IBGE_2013.csv", index_col = 0) 

# Cria um intervalo entre 80 e 90 para somar as idades
interval = [str(i) for i in range(80,90)] + ["90+"]
            
# Soma as idades e cria uma nova linha no dataframe
pop_homens.loc["80+"] = pop_homens.loc[interval].sum(axis=0)
pop_mulheres.loc["80+"] = pop_mulheres.loc[interval].sum(axis=0)

# Remove as idades entre 80 e 90
pop_homens.drop(interval, inplace=True)
pop_mulheres.drop(interval, inplace=True)

In [7]:
pop_homens.head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060
0,1774654,1790542,1767804,1744989,1721442,1697264,1672682,1647974,1623412,1599362,...,988361,977183,966313,955717,945363,935224,925279,915515,905910,896440
1,1768376,1762944,1779556,1757644,1735613,1712808,1689342,1665430,1641346,1617369,...,999045,987575,976411,965554,954970,944628,934500,924566,914812,905218
2,1763299,1763920,1758749,1775577,1753971,1732251,1709769,1686636,1663060,1639305,...,1010401,998640,987179,976024,965175,954599,944264,934143,924216,914469
3,1759424,1760566,1761316,1756286,1773236,1751808,1730282,1707999,1685075,1661706,...,1022190,1010116,998362,986907,975758,964914,954343,944013,933897,923975
4,1756766,1757342,1758574,1759415,1754495,1771538,1750257,1728882,1706762,1683996,...,1034360,1021959,1009890,998141,986691,975546,964706,954140,943813,933701